<?php
// Member home: filter recipes with bound parameters, then render newest community posts first.
require_once __DIR__ . '/helpers.php'; require_login();
$term = trim((string)($_GET['q'] ?? '')); $category = filter_var($_GET['category'] ?? '', FILTER_VALIDATE_INT);
$sql = 'SELECT r.*, c.name category, u.name author, (SELECT COUNT(*) FROM comments cm WHERE cm.recipe_id=r.id) comment_count, (SELECT COUNT(*) FROM favorites f WHERE f.recipe_id=r.id) favorite_count, EXISTS(SELECT 1 FROM favorites mine WHERE mine.recipe_id=r.id AND mine.user_id=?) is_favorite FROM recipes r JOIN categories c ON c.id=r.category_id JOIN users u ON u.id=r.user_id';
$where = []; $params = [(int)$_SESSION['user']['id']];
if ($term !== '') { $where[] = '(r.title LIKE ? OR r.description LIKE ? OR EXISTS(SELECT 1 FROM ingredients i WHERE i.recipe_id=r.id AND i.ingredient LIKE ?))'; $like='%'.$term.'%'; array_push($params,$like,$like,$like); }
if ($category) { $where[] = 'r.category_id=?'; $params[]=$category; }
if ($where) $sql .= ' WHERE '.implode(' AND ', $where);
$sql .= ' ORDER BY r.created_at DESC, r.id DESC'; $stmt=$pdo->prepare($sql); $stmt->execute($params); $recipes=$stmt->fetchAll(); $cats=categories($pdo);
$pageTitle='Community recipes'; require __DIR__.'/header.php';
?>
<section class="hero"><div class="hero-copy"><p class="eyebrow">OUR NEIGHBORHOOD RECIPE BOOK</p><h1>Good food brings<br><em>us together.</em></h1><p>Recipes from home cooks around the barangay, made to be passed around.</p><a class="button button-light" href="recipe_form.php">Share what’s cooking <span>↗</span></a></div><div class="hero-art" aria-hidden="true"><div class="sun"></div><span class="hero-doodle">✳</span><div class="plate"><div class="plate-inner"><span>🍲</span></div></div><div class="hero-note">lutong bahay,<br>kwentong atin</div></div><div class="hero-bottom"><span>FRESH FROM OUR COMMUNITY</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="discover"><div class="section-heading"><div><p class="eyebrow">THE COMMUNITY TABLE</p><h2><?= $term !== '' ? 'Search results' : 'What’s cooking' ?></h2></div><span class="result-count"><?= count($recipes) ?> <?= count($recipes)===1?'recipe':'recipes' ?></span></div>
<form class="filters" method="get"><label class="searchbox"><span>⌕</span><input name="q" value="<?= h($term) ?>" placeholder="Find a dish or ingredient…" aria-label="Search recipes"></label><label class="select-wrap"><span class="sr-only">Category</span><select name="category"><option value="">All categories</option><?php foreach($cats as $cat): ?><option value="<?= (int)$cat['id'] ?>" <?= $category===(int)$cat['id']?'selected':'' ?>><?= h($cat['name']) ?></option><?php endforeach; ?></select></label><button class="button button-dark">Find recipes</button><?php if($term!==''||$category): ?><a class="clear-link" href="index.php">Clear</a><?php endif; ?></form>
<?php if($recipes): ?><div class="recipe-grid"><?php foreach($recipes as $i=>$r): ?><article class="recipe-card"><a class="card-image image-<?= $i%4 ?>" href="recipe.php?id=<?= (int)$r['id'] ?>"><span class="category-pill"><?= h($r['category']) ?></span><span class="dish-illustration" aria-hidden="true"><?= ['🍛','🥘','🍜','🍮'][$i%4] ?></span><span class="image-caption">LUTONG BAHAY</span></a><div class="card-body"><div class="card-meta"><span><?= (int)$r['cook_minutes'] ?> MIN <b>·</b> <?= (int)$r['servings'] ?> SERVINGS</span><span>♡ <?= (int)$r['favorite_count'] ?></span></div><h3><a href="recipe.php?id=<?= (int)$r['id'] ?>"><?= h($r['title']) ?></a></h3><p><?= h($r['description']) ?></p><div class="card-bottom"><span>by <b><?= h($r['author']) ?></b></span><span><?= (int)$r['comment_count'] ?> comments</span><button class="favorite-button <?= $r['is_favorite']?'is-favorite':'' ?>" type="button" data-favorite="<?= (int)$r['id'] ?>" aria-pressed="<?= $r['is_favorite']?'true':'false' ?>" title="Toggle favorite">♥</button></div></div></article><?php endforeach; ?></div><?php else: ?><div class="empty-state"><span>🥄</span><h3>No recipes on this plate yet.</h3><p>Try another search, or be the first to share something delicious.</p><a class="button button-dark" href="recipe_form.php">Share a recipe</a></div><?php endif; ?>
</section>
<?php require __DIR__.'/footer.php'; ?>
