<?php
// Recipe detail page: show ingredients, steps, favorite state, comments, and accept new member comments.
require_once __DIR__.'/helpers.php';require_login();$id=filter_var($_GET['id']??null,FILTER_VALIDATE_INT);if(!$id){http_response_code(404);exit('Recipe not found.');}$recipeModel=new Recipe($pdo);
$recipe=$recipeModel->findForMember((int)$id,(int)$_SESSION['user']['id']);if(!$recipe){http_response_code(404);exit('Recipe not found.');}
$ingredients=$recipeModel->ingredients((int)$id);$q=$pdo->prepare('SELECT c.*,u.name author FROM comments c JOIN users u ON u.id=c.user_id WHERE c.recipe_id=? ORDER BY c.created_at ASC');$q->execute([$id]);$comments=$q->fetchAll();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='comment'){verify_csrf();$body=trim((string)($_POST['body']??''));if(mb_strlen($body)<2||mb_strlen($body)>1000)$error='Comment must be 2–1,000 characters.';else{$q=$pdo->prepare('INSERT INTO comments(recipe_id,user_id,body) VALUES(?,?,?)');$q->execute([$id,(int)$_SESSION['user']['id'],$body]);flash('Your comment has been added.');header('Location: recipe.php?id='.$id.'#comments');exit;}}
$pageTitle=$recipe['title'];require __DIR__.'/header.php';?>
<article class="recipe-detail"><a class="back-link" href="index.php">← All recipes</a><div class="detail-cover"><div class="detail-cover-copy"><span class="category-pill"><?= h($recipe['category']) ?></span><h1><?= h($recipe['title']) ?></h1><p><?= h($recipe['description']) ?></p><div class="detail-by">Shared by <b><?= h($recipe['author']) ?></b> · <?= date('M j, Y',strtotime($recipe['created_at'])) ?><?php if($recipe['edited_at']): ?><span class="edited-note">· Edited <?= date('M j, Y',strtotime($recipe['edited_at'])) ?></span><?php endif; ?></div></div><div class="detail-art" aria-hidden="true">🍲</div></div><div class="detail-toolbar"><div class="recipe-facts"><span>◷ <b><?= (int)$recipe['cook_minutes'] ?> min</b></span><span>♧ <b><?= (int)$recipe['servings'] ?> servings</b></span><span>♡ <b data-favorite-count><?= (int)$recipe['favorite_count'] ?></b> saves</span></div><div class="detail-actions"><button class="button button-outline favorite-toggle <?= $recipe['is_favorite']?'is-favorite':'' ?>" type="button" data-favorite="<?= (int)$id ?>" aria-pressed="<?= $recipe['is_favorite']?'true':'false' ?>"><?= $recipe['is_favorite']?'♥ Saved':'♡ Save recipe' ?></button><?php if((int)$recipe['user_id']===(int)$_SESSION['user']['id']): ?><a class="text-action" href="recipe_form.php?id=<?= (int)$id ?>">Edit recipe</a><form class="inline" method="post" action="recipe_delete.php" data-confirm="Delete this recipe and its comments?"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$id ?>"><button class="text-action danger" type="submit">Delete</button></form><?php endif; ?></div></div>
<div class="detail-columns"><section class="ingredients-panel"><p class="eyebrow">GATHER YOUR INGREDIENTS</p><h2>What you’ll need</h2><ul class="ingredient-checklist"><?php foreach($ingredients as $ingredient): ?><li><label><input type="checkbox"><span><?= h($ingredient['ingredient']) ?></span></label></li><?php endforeach; ?></ul><p class="tip-box">A little extra love is always the secret ingredient. <b>♡</b></p></section><section class="steps-panel"><p class="eyebrow">LET’S GET COOKING</p><h2>Here’s how</h2><ol class="steps-list"><?php foreach(preg_split('/\R+/',trim($recipe['instructions'])) as $step): if(trim($step)==='')continue; ?><li><span class="step-dot"></span><p><?= h(trim($step)) ?></p></li><?php endforeach; ?></ol></section></div></article>
<section class="comments-section" id="comments"><div class="section-heading"><div><p class="eyebrow">AROUND THE TABLE</p><h2>Notes from neighbors <span class="comment-total"><?= count($comments) ?></span></h2></div></div><?php if($error): ?><div class="form-errors"><p><?= h($error) ?></p></div><?php endif; ?><form method="post" class="comment-form"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="comment"><label class="sr-only" for="comment-body">Add a comment</label><textarea id="comment-body" name="body" minlength="2" maxlength="1000" required placeholder="Share a thought, a tip, or a thank you…"></textarea><button class="button button-dark">Leave a note <span>→</span></button></form><div class="comment-list"><?php foreach($comments as $comment): ?><article class="comment"><div class="avatar"><?= h(mb_strtoupper(mb_substr($comment['author'],0,1))) ?></div><div class="comment-content"><div class="comment-meta"><b><?= h($comment['author']) ?></b><time><?= date('M j, Y · g:i a',strtotime($comment['created_at'])) ?><?php if($comment['edited_at']): ?> · edited<?php endif; ?></time><?php if((int)$comment['user_id']===(int)$_SESSION['user']['id']): ?><span class="comment-controls"><a href="comment_form.php?id=<?= (int)$comment['id'] ?>">Edit</a><form class="inline" action="comment_delete.php" method="post" data-confirm="Delete this comment?"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$comment['id'] ?>"><button type="submit">Delete</button></form></span><?php endif; ?></div><p><?= nl2br(h($comment['body'])) ?></p></div></article><?php endforeach; ?><?php if(!$comments): ?><p class="muted">No notes yet. Be the first neighbor to leave one.</p><?php endif; ?></div></section>
<?php require __DIR__.'/footer.php';?>
